linters-settings:
  goimports:
    local-prefixes: github.com/azuline/cmponly

run:
  go: "1.18"
  tests: true
  timeout: 5m

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - errcheck
    - errorlint
    - exhaustive
    - gochecknoinits
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - nolintlint
    - revive
    - staticcheck
    - typecheck
    - unparam
    - unused
    - whitespace

issues:
  max-same-issues: 10000
  max-issues-per-linter: 10000
